name: hola-mundo
run-name: Workflow para hola mundo
on: [push]
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Correr script
        run: python main.py
