name: secretos
run-name: workflow secretos
on: 
  workflow_dispatch
jobs:
  imprimir-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: imprime las variables
        run: echo $var.nombre tu contrasena es $secrets.contrasena
